### ISSUE TITLE
privacy info & build/installation howto

### ISSUE THREAD

**Issue by foreveremain** [Vis4Sense/SenseMapExtension#129]
Hi!  I discovered this project after stumbling across the SenseMap paper from VAST 2016. I'm interested in trying it out for my own needs as an academic who frequently explores a large number of papers and online resources, but I was stopped by two things:

1 - the lack of build instructions. Rather than linking to a blog post could you provide a tldr; and a description of the preferred toolchain/procedure that contributors should follow ?

2 - privacy statement. Any browser extension needs to clearly state something about what it does with our precious personal activity data, otherwise users like me are highly unlikely to adopt. 

Thanks in advance !

**Comment by kaidatavis** [comment]
Hi Jim, 

For 1, there is no build needed if you mean transpiling js code. The extension is written in vanila js, and it should run by loading as a local extension in Chrome

For 2, indeed there should be a privacy statement. The 'rebuild-mvc' branch includes the code that aims to save the data to a server, but that was not finished, i.e., not working. The old version is in the 'master' branch, and it can only save file locally (by default does not save anything). 

If you just want to try the extension, the easiest way is probably install it from the chrome web store. 
- The old version: https://chrome.google.com/webstore/detail/sensemap/agljnpanahlilmpipaeflmnjkiiecfjb
- The new version: https://chrome.google.com/webstore/detail/historymap/jjgdemkolpjjdkgmfgolldlnoghhodlj

**Comment by foreveremain** [comment]
Thanks Kai - very much appreciated !  I muddled my way through the
extension docs myself after lodging the issue and felt a little sheepish
about asking for build instructions :)

Was the save functionality so that the history tree could be
persisted beyond a particular browsing session ?  It sounds like for the
moment, no browsing history goes beyond the user's browser session unless
they choose to save it, so all remains private.

I'll try out both versions and perhaps drop you a line directly rather than
via a github issue.

**Comment by kaidatavis** [comment]
> Was the save functionality so that the history tree could be persisted beyond a particular browsing session ? It sounds like for the moment, no browsing history goes beyond the user's browser session unless they choose to save it, so all remains private.

The 'saving' features only works in the older version, which is called 'sensemap'. It creates a zip file include the session information (a couple of json files plus the webpage screenshots). The zip file can be opened later by sensemap to continue the session.

**Comment by bluecamel** [comment]
The link to the blog post is broken.  Also, the links on https://vis4sense.github.io/sensemap/index.html to install from the Chrome store are broken.  What is the current recommended way to install this?

**Comment by kaidatavis** [comment]
> The link to the blog post is broken. Also, the links on https://vis4sense.github.io/sensemap/index.html to install from the Chrome store are broken. What is the current recommended way to install this?

Thanks for point this out. The old 'sensemap' extension is no long maintained and removed from the chrome web store. I updated the page on vis4sense.github.io to reflect this.

If you still want to try the old 'sensemap', it is in the 'master' branch of this repository. You need to install the extension from the source code ([instruction](https://dev.to/ben/how-to-install-chrome-extensions-manually-from-github-1612))

The latest version is in the 'rebuild-mvc' brach, which is not quite finished. Again, it needs to be installed from the source code similar to sensemap.

**Comment by kaidatavis** [comment]
Please let me know if anyone can help with the development of the historymap extension. Any help will be useful.
