### ISSUE TITLE
Manifest version deprecation warning

### ISSUE THREAD

**Issue by joao-tonsic-gympass** [Vis4Sense/SenseMapExtension#131]
Hi folks, just to let you know, I installed the extension right now and there is a warning in Chrome telling:

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

I think this is low priority and do with it what you will, just wanted to let you know.

Thanks for the effort guys!
 
![image](https://user-images.githubusercontent.com/116071973/224026698-337a820b-ffff-4d85-92ca-0ae3d118f93d.png)

![image](https://user-images.githubusercontent.com/116071973/224026814-b282af12-3661-4bb4-be54-b1e21f0387b8.png)

**Comment by kaidatavis** [comment]
Indeed, this is on the todo list. Google made this a requirement recently. Hopefully it is not too difficult.

**Comment by kaidatavis** [comment]
The manifest is updated to v3 now.
