### ISSUE TITLE
Layout library

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/SenseMapExtension#138]
Requirement:
1. support tree or hierarchy
2. consider node size for layout 

Candidates
1. [mxgraph](https://jgraph.github.io/mxgraph/) or [maxGraph](https://github.com/maxGraph/maxGraph)
1. [CytoScape](https://js.cytoscape.org/) and [ELK layout](https://eclipse.dev/elk/)

**Comment by kaidatavis** [comment]
@Jeffrey-D-Pierce implemented an option to use only html and css for this. Currently this is implemented as a React component, and the next step is to see if/how to get it to work with plain JS.

**Comment by Yuu-Han** [comment]
I checked with Hanning. He did not use d3 but implemented the tree layout himself, which calculates the node positions in a  bottom-up manner.

The code needs slight modification to allow different leave sizes (see the comment in the following code).

```JavaScript
let TreeStructureLayout = {
  methods: {
    loadTreeData (root, level, depth) {
      let data = getAllNodes()
      let rnode = {
        'hid': root,
        'level': level,
        'kids': [],
        'isLeave': false,
      }
      if (data[root].kids==undefined) {
        rnode.isLeave = true
        return rnode
      }
      if (depth == 0) {
        return rnode
      }
      for (let i in data[root].kids) {
        rnode.kids.push(this.loadTreeData(data[root].kids[i], level + 1, depth - 1))
      }
      return rnode
    },
    calTreeWidth (root) {
      let w = 0
      if (root.kids.length == 0) {
        root['width'] = 1 /** TODO: set custom node width */
        return
      }
      for (let i in root.kids) {
        this.calTreeWidth(root.kids[i])
        w += root.kids[i].width
      }
      root['width'] = w
    },
    calTreeLayout (root) {
      let offset = root.offset
      let cover = root.cover
      for (let i in root.kids) {
        root.kids[i]['offset'] = offset
        let c = cover * root.kids[i].width / root.width
        offset += c
        root.kids[i]['cover'] = c
        this.calTreeLayout(root.kids[i])
      }
    },
  }
}
```

This code is copied from a vue project and might need slight transformation to plain JS.

**Comment by Yuu-Han** [comment]
By the way, I am investigating developing a tree visualisation method proposed in my previous work to a library, so I just had a look at [treevis.net](https://treevis.net/).

I found the Hi-tree paper [1]. It looks appealing. Tim further proposed a layout algorithm of it [2]. It is a bit complex for this project but I'm not sure if Tim considered this layout when developing [Cola.js](https://ialab.it.monash.edu/webcola/). If yes Cola should support the layered layout (by setting some special constraints I guess?).

- [1] Hi-Trees and Their Layout (TVCG 2011) [doi](https://doi.org/10.1109/TVCG.2010.45)
- [2] Hi-tree Layout Using Quadratic Programming (International Conference on Theory and Application of Diagrams 2010) [doi](https://doi.org/10.1007/978-3-642-14600-8_20)

**Comment by kaidatavis** [comment]
It should be quite easy to use any tree layout. In `hmController.js`, the `displayTree(hmPages)` (close to the end) calls the tree layout. This can be replaced with any other layout function call, such as `hiTree(hmPages)`. `hmPages` is an array of webpages user visited with the  link recorded as the `parent` (see `hmModel.js`).

**Comment by Yuu-Han** [comment]
Just to note some tree layout algorithms and libraries I randomly discovered

- [Visualizing Evolving Trees](https://ryngray.github.io/dynamic-trees/)
  - [github](https://github.com/abureyanahmed/evolving_tree)
- Drawing dynamic trees (Moen 1990) [doi](https://doi.org/10.1109/52.56447)

**Comment by Yuu-Han** [comment]
I saw @Jeffrey-D-Pierce updated the tree layout using HTML (it's beautiful!). I pushed a simple layout using d3 as well (#141 ).

Currently the behaviour of the two approaches (for vertical tree) is the same (without compact optimisation). This is not very nice when the scale of the tree gets large. Maybe we need to come back to this later (using a library or implementing optimisation algorithm), depending on the priority?

**Comment by Yuu-Han** [comment]
[Understanding sequence and reply relationships within email conversations: a mixed-model visualization (CHI 2003)](https://dl.acm.org/doi/10.1145/642611.642674)

This can be an alternative to the vertical layout. It shows the temporal sequence.

<img width="703" alt="image" src="https://github.com/Vis4Sense/HistoryMap/assets/72588097/96f5e6b8-c941-4729-8c5d-ace52b3a8df4">

**Comment by kaidatavis** [comment]
> This can be an alternative to the vertical layout. It shows the temporal sequence.

This is very interesting, like a flipped version of the current vertical layout (along the 45 degree diagonal?). It will be interesting to test it out, comparing to the current vertical and other layouts.

**Comment by Yuu-Han** [comment]
Layout libraries to investigate:

- <https://github.com/maxGraph/maxGraph>
  - A community rebuild of [mxgraph](https://github.com/jgraph/mxgraph)
  - It uses TypeScript
