### ISSUE TITLE
Allow user to choose tree layout

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/SenseMapExtension#145]

**Comment by Jeffrey-D-Pierce** [comment]
I created a popup with the ability to select and open the Vector, HTML, or TBD experience. With displayTree(hmPage) as the standard interface for each, both experiences (Vector and HTML) work at the same time (both can be open) using the same controller. We should consider putting the save and load functionality into the popup.

**Comment by Yuu-Han** [comment]
The popup looks nice :-)

> We should consider putting the save and load functionality into the popup.

Have added it to #140

**Comment by kaidatavis** [comment]
@Jeffrey-D-Pierce, nice work! Would it be easier for the user to select the different layouts (vector, html, etc.) on the HistoryMap page instead of the popup, similar to how you did for vertical, horizontal, etc.? Also, a radio button for layout would be nicer than a drop-down menu :-)

**Comment by kaidatavis** [comment]
@Yuu-Han, did you push the changes? I just did a pull, and don't see the save/load in the popup?

**Comment by Yuu-Han** [comment]
not yet, i just added it as a todo item and have not made any changes
