### ISSUE TITLE
Activate tab on clicking tree node

### ISSUE THREAD

**Issue by Yuu-Han** [Vis4Sense/SenseMapExtension#148]

**Comment by Yuu-Han** [comment]
It is easy to find and activate a page that has the same url with the node (or create a new one if it is already closed), but a bit tricky to maintain `hmPages`. My major concern is how to maintain `tabId`.

Considering the following scenario:

The user navigated through multiple pages (i.e., p1, p2, ...) within the tab, which results in multiple `hmPage`s with the same (tab) `id`. When the user clicks node p1, the page is closed but the tab is still active, so there are some options:

- Option 1: update that tab with p1's `url`, so that we do not need to update the tab `id` of p1
- Option 2: open a new tab and update the tab `id` of p1
- Option 3: open a new tab and add it as a new node in the tree

(There are similar issues with opening a closed page.)

For option 1 & 2, new nodes are to be added from p1, but what if the user opens another p2' that has the same url with p2? is p2' going to be a new child node or should it be merged with p2? Also, if the tab `id` is changed, `hmPages` might not be enough for saving the session (for debug aim)?

**Comment by kaidatavis** [comment]
Very good point. I think there are two parts of this, 1) where to (re)open the page/url, and 2) how to update the (internal) data structure (hmPages).

For 1), my preference is probably open it in a new tab; updating an existing tab may cause the user to lose something that he/she still needs.

For 2), it is a bit trickers. First, if user opens the same url in a new tab, I think this should be treated as a new node in historyMap. For example, user can open multiple google search pages and each for a different topic; it does not make much sense to me to include all the google search starting page as one node. 

I am not sure how best to update hmPages; maybe branch off from the old node will be the better option? We can discuss this at the meeting.

**Comment by Yuu-Han** [comment]
This is completed. Clicking an opened page will activate the corresponding tab and clicking a closed page will open a new tab. The original hmPage object is updated (not adding a new node to hmPages).
