### ISSUE TITLE
Save session to / load session from local storage

### ISSUE THREAD

**Issue by Yuu-Han** [Vis4Sense/SenseMapExtension#154]

**Comment by Yuu-Han** [comment]
An alternative to local storage (10mb limit) is [IndexedDB](https://javascript.info/indexeddb). It does not have a specific limit on the size of storage, only depending on the browser and disk ([maximum item size in IndexedDB](https://stackoverflow.com/questions/5692820/maximum-item-size-in-indexeddb)).

**Comment by kaidatavis** [comment]
Yes. I haven't tried this myself, but I heard it is not that easy to use. I think Jeff might have mentioned this as well.

**Comment by Yuu-Han** [comment]
This commit (cd403aaa83aaea526bea30c67a11abc5eb18cd49) automatically saves the `hmPages` to local storage when the array is updated and loads the saved array when historymap is opened (not sure if the timing of saving and loading needs to be changed).
