### ISSUE TITLE
Whether to migrate to Vue/React+TypeScript?

### ISSUE THREAD

**Issue by Yuu-Han** [Vis4Sense/SenseMapExtension#157]

**Comment by kaidatavis** [comment]
Not for now. Probably when the chrome gets more complex.

**Comment by Yuu-Han** [comment]
I think we should use a framework. There have been a lot of useful libraries that make it very easy to sync data (e.g., [vueuse](https://vueuse.org/)), communicate messages (e.g., [webext-bridg](https://serversideup.net/open-source/webext-bridge/)), etc.

Taking data sync as an example (#174), it only requires one line to create a reactive hmpages array:

```javascript
const { data: hmPages } = useBrowserLocalStorage('hm-pages', [] as HmPage[])
```

It is a two-way binding, which means the storage is automatically updated when the array changes:

```javascript
hmPages.value = [...hmPages.value, newHmPage]
```

This utility can be used in both background and extension views, all synchronised with the local storage.

I believe the benefits outweigh the costs of learning :-)

---

I tried a few boilerplate templates for using vue to develop web extension. The features are similar (vite+vue+ts, hmr, unocss/tailwindcss, supporting firefox besides chrome, etc.). But not all work as expected (the browser is always updating).

- [vite-vue3-browser-extension-v3](https://github.com/mubaidr/vite-vue3-browser-extension-v3)
  - For now this works best (no issues encountered yet).
- [vitesse-webext](https://github.com/antfu-collective/vitesse-webext)
  - I like its architecture and style, but its background/content script HMR is not working at the moment.
- [create-chrome-ext](https://github.com/guocaoyi/create-chrome-ext)
  - It is the first boilerplate I tried. It is also nice but somehow it did not work after a chrome update a few month ago.

**Comment by kaidatavis** [comment]
You can decide :-) The first one look most up to date and comes with several boiler plate pages.

**Comment by Yuu-Han** [comment]
found some new frameworks for cross-browser web extensions:
- wxt: https://github.com/wxt-dev/wxt
- crxjs: https://github.com/crxjs/chrome-extension-tools

**Comment by Yuu-Han** [comment]
wxt is great :)
