### ISSUE TITLE
Encode visible tab on historymap

### ISSUE THREAD

**Issue by Yuu-Han** [Vis4Sense/SenseMapExtension#169]
This helps to locate the current tab on historymap.

**Comment by Yuu-Han** [comment]
b0b11363129a07f2d9ea8ee62b40daed01c340d7

When a tab is activated, try to locate the page in `hmPages`

- If the page is found (same tab id, same url), set the node as visible and scroll to it
- Otherwise, add a virtual node to the bottom of the hm tree
  - How to save the node? Automatically add it to the array or let the user decide?
- Related to #171, ideally if a page with the same url but different tab id is found, we should remind the user.

Issues:

- [x] The `chrome.tabs.onActivated` event might be fired earlier than `chrome.webNavigation.onCommitted` event. In this case, when a new page is opened, both the newly added node and the virtual node are displayed.
  - Fixed, not using virtual node (ffc7522515e0e03d06802df8902bb531d65ff3fa), update visibility of reopened page (d2b1369f27002023d2934ff4fe876a01ca5584ef)
- [x] The visible node is not updated when the new page is opened in the same tab (as no new tab is created, there is no tab activate event).
  - Fixed (504b0fd657f79b5f142cf4e2d302f617af760047, fb35d864b3a20f7baa56966de7e0feb50b0d9829)

**Comment by kaidatavis** [comment]
Is it possible that an activated tab is not a node in history map?

**Comment by Yuu-Han** [comment]
Yes. The current behaviour is adding a virtual node.

> - Otherwise, add a virtual node to the bottom of the hm tree
>   - How to save the node? Automatically add it to the array or let the user decide?

I haven't decided whether to directly add it to hmPages or add on user's demand.

**Comment by Yuu-Han** [comment]
Decision: add the page to `hmPages` on activating the tab.

**Comment by Yuu-Han** [comment]
Fixed issues in https://github.com/Vis4Sense/HistoryMap/issues/169#issuecomment-2155889901.
